### ISSUE TITLE
Build Failure: bcrypt Module Not Found During Production Build

### ISSUE THREAD

**Issue by ibrahimkonuk** [vercel/next-learn#1034]
Hi Team,

I'm encountering a build failure while following the Next.js dashboard tutorial ([https://nextjs.org/learn/dashboard-app/getting-started](https://nextjs.org/learn/dashboard-app/getting-started)). The issue occurs during the production build process (`pnpm build`).

#### Description of the Issue

The build process fails with a "Module Not Found" error related to the `bcrypt` package. Specifically, the error message indicates that the native bindings for `bcrypt` cannot be located.

```
nextjs-dashboard % pnpm build
> @ build /Users/.../nextjs-dashboard
> next build

   ▲ Next.js 15.1.6

   Creating an optimized production build ...
 ✓ Compiled successfully
 ✓ Linting and checking validity of types    
   Collecting page data  ..[Error: Cannot find module '.../nextjs-dashboard/node_modules/.pnpm/bcrypt@5.1.1/node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node'
Require stack:
- .../nextjs-dashboard/node_modules/.pnpm/bcrypt@5.1.1/node_modules/bcrypt/bcrypt.js
- .../nextjs-dashboard/.next/server/app/seed/route.js
- .../nextjs-dashboard/node_modules/.pnpm/next@15.1.6_react-dom@19.0.0_react@19.0.0__react@19.0.0/node_modules/next/dist/server/require.js
- .../nextjs-dashboard/node_modules/.pnpm/next@15.1.6_react-dom@19.0.0_react@19.0.0__react@19.0.0/node_modules/next/dist/server/load-components.js
- .../nextjs-dashboard/node_modules/.pnpm/next@15.1.6_react-dom@19.0.0_react@19.0.0__react@19.0.0/node_modules/next/dist/build/utils.js
- .../nextjs-dashboard/node_modules/.pnpm/next@15.1.6_react-dom@19.0.0_react@19.0.0__react@19.0.0/node_modules/next/dist/build/worker.js
- .../nextjs-dashboard/node_modules/.pnpm/next@15.1.6_react-dom@19.0.0_react@19.0.0__react@19.0.0/node_modules/next/dist/compiled/jest-worker/processChild.js] {
  code: 'MODULE_NOT_FOUND',
  requireStack: [Array]
}

> Build error occurred
[Error: Failed to collect page data for /seed] { type: 'Error' }
 ELIFECYCLE  Command failed with exit code 1.
```

#### Context

This issue occurs during the `pnpm build` command, specifically when Next.js is attempting to collect page data. The error prevents a production build from being created.

#### Environment

- **Next.js version**: 15.1.6 (as per the tutorial)
- **pnpm version**: 10.6.5
- **Node.js version**: v20.18.0
- **Package Manager**: pnpm

#### Additional Information

During `pnpm install`, the following warning was also displayed:

```
Warning
Ignored build scripts: bcrypt, sharp.
Run "pnpm approve-builds" to pick which dependencies should
be allowed to run scripts.
```

#### Possible Root Cause

The `bcrypt` package relies on native bindings, which may not be correctly compiled or located during the build process, especially in a Next.js environment. The warning about ignored build scripts could be related.

#### Suggested Solution/Workaround

A workaround that resolves the issue is to replace `bcrypt` with `bcryptjs`. `bcryptjs` is a pure JavaScript implementation and does not require native bindings.

```
pnpm remove bcrypt
pnpm add bcryptjs
```

#### Impact

This build failure prevents users from completing the Next.js dashboard tutorial and deploying a production-ready application.

Thank you for your attention to this matter. I hope this information is helpful in resolving the issue.

**Comment by Joysca** [comment]
Another option works, delete the project in the Vercel and import the project again and add the environment variable of postgreSql

**Comment by jemiks** [comment]
To fix the bcrypt module error, you can replace bcrypt with bcryptjs,

**Comment by SadBatya** [comment]
if you want to fix this bug. Now you need to remove the bcrypt package and add the bcryptjs package

pnpm remove bcrypt
pnpm add bcrypt
pnpm add -D @types/bcrypt

Everything works for me now. Good luck with your studies!

**Comment by JunniKunni** [comment]
The combination of ibrahimkonuk's suggested solution/workaround, jemiks comment, and SadBatya's comment fixed this for me!

Steps I took:
1. pnpm remove becrypt
2. pnpm add bcryptjs
3. Make sure bcrypt is no longer used as the library to import from
  - Only file affected in the tutorial is app/seed/route.ts on line 1.
    - Change it from `import bcrypt from 'bcrypt';` to `import bcrypt from 'bcryptjs';`

**Comment by ekeyme** [comment]
```shell
rm -rf node_modules/ &&  pnpm i
pnpm approve-builds  
# - > select bcrypt to approve it for build
pnpm run build # or push update to github
```

those steps should solve this issue.

**Comment by Robert126** [comment]
Thank you all. I installed the bcryptjs package.

I have the following problem:
Seed the database by running:
http://localhost:3000/seed
I am getting a:
 GET /seed 500 in 21ms (compile: 4ms, render: 17ms)

And in the prosgresql log:
 LOG:  invalid length of startup packet

I found in the package.json that bcrypt still exists.
```
{
  "private": true,
  "scripts": {
    "build": "next build",
    "dev": "next dev --turbopack",
    "start": "next start"
  },
  "dependencies": {
    "@heroicons/react": "^2.2.0",
    "@tailwindcss/forms": "^0.5.10",
    "autoprefixer": "10.4.20",
    "bcrypt": "^5.1.1",
    "bcryptjs": "^3.0.3",
    "clsx": "^2.1.1",
    "next": "latest",
    "next-auth": "5.0.0-beta.25",
    "postcss": "8.5.1",
    "postgres": "^3.4.6",
    "react": "latest",
    "react-dom": "latest",
    "tailwindcss": "3.4.17",
    "typescript": "5.7.3",
    "use-debounce": "^10.0.4",
    "zod": "^3.25.17"
  },
  "devDependencies": {
    "@types/bcrypt": "^5.0.2",
    "@types/node": "22.10.7",
    "@types/react": "19.0.7",
    "@types/react-dom": "19.0.3"
  },
  "pnpm": {
    "onlyBuiltDependencies": [
      "bcrypt",
      "sharp"
    ]
  }
}
```

my .env file:
```
POSTGRES_URL="postgresql://user:password@localhost:5432/nextjs_dashboard"

# Even the change:
POSTGRES_URL="postgres://user:password@localhost:5432/nextjs_dashboard"
```
 GET /seed 500 in 54ms (compile: 33ms, render: 21ms)
LOG:  invalid length of startup packet

I can connect to the database with pgadmin and the specific user/ password.

Hopefully someone can help me out?

On forhand thank you for your help!
